// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/joescharf/twitterprofile/v2/ent/stripe"
)

// Stripe is the model entity for the Stripe schema.
type Stripe struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// APIKey holds the value of the "api_key" field.
	APIKey string `json:"api_key,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt     time.Time `json:"updated_at,omitempty"`
	user_accounts *int
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Stripe) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case stripe.FieldID:
			values[i] = new(sql.NullInt64)
		case stripe.FieldAPIKey:
			values[i] = new(sql.NullString)
		case stripe.FieldCreatedAt, stripe.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case stripe.ForeignKeys[0]: // user_accounts
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Stripe", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Stripe fields.
func (s *Stripe) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stripe.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case stripe.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				s.APIKey = value.String
			}
		case stripe.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case stripe.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		case stripe.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_accounts", value)
			} else if value.Valid {
				s.user_accounts = new(int)
				*s.user_accounts = int(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Stripe.
// Note that you need to call Stripe.Unwrap() before calling this method if this Stripe
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Stripe) Update() *StripeUpdateOne {
	return (&StripeClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Stripe entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Stripe) Unwrap() *Stripe {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Stripe is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Stripe) String() string {
	var builder strings.Builder
	builder.WriteString("Stripe(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", api_key=")
	builder.WriteString(s.APIKey)
	builder.WriteString(", created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Stripes is a parsable slice of Stripe.
type Stripes []*Stripe

func (s Stripes) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
