// Code generated by entc, DO NOT EDIT.

package user

import (
	"time"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScreenName holds the string denoting the screen_name field in the database.
	FieldScreenName = "screen_name"
	// FieldTwitterUserID holds the string denoting the twitter_user_id field in the database.
	FieldTwitterUserID = "twitter_user_id"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldTokenSecret holds the string denoting the token_secret field in the database.
	FieldTokenSecret = "token_secret"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldScreenName,
	FieldTwitterUserID,
	FieldToken,
	FieldTokenSecret,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
