// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Stripe is the predicate function for stripe builders.
type Stripe func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
